/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YDDXoLu7Rlq
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { format } from "date-fns";
import { Calendar, ChevronRight, MapPin, User, Users } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { Button } from "~/components/ui/button";
import { cn } from "~/lib/utils";

interface HackathonPageProps {
  name: string;
  subtitle?: string | null;
  startDate: Date;
  endDate: Date;
  description: string;
  location: string;
  organizer: {
    firstName: string;
    lastName: string;
  };
  photo: string;
  registrationOpen: Date;
  registrationClose: Date;
  minTeamSize: number;
  maxTeamSize: number;
  id: number;
}

export function HackathonPage({
  name,
  subtitle,
  startDate,
  endDate,
  description,
  location,
  organizer,
  photo,
  registrationClose,
  registrationOpen,
  minTeamSize,
  maxTeamSize,
  id,
}: HackathonPageProps) {
  const startYear = new Date(startDate).getFullYear();
  const endYear = new Date(endDate).getFullYear();

  return (
    <div className="flex min-h-[100dvh] flex-col">
      <section className="w-full border-b bg-black text-primary">
        <div className="flex flex-col justify-center space-y-6 py-12 md:py-24 lg:py-32">
          <div className="space-y-4">
            <h1 className="text-wrap text-4xl font-bold tracking-tighter sm:text-6xl xl:text-7xl/none">
              {name}
            </h1>
            <p className="max-w-[600px] text-primary/80 md:text-xl">
              {subtitle}
            </p>
            <div className="flex flex-col items-center gap-4 min-[400px]:flex-row">
              <div className="flex items-center gap-2">
                <Calendar className="h-5 w-5" />
                <div>
                  <div className="font-medium">
                    {startYear !== endYear ? (
                      <>
                        {format(
                          new Date(startDate).toISOString(),
                          "MMMM d, yyyy",
                        )}{" "}
                        -{" "}
                        {format(
                          new Date(endDate).toISOString(),
                          "MMMM d, yyyy",
                        )}
                      </>
                    ) : (
                      <>
                        {format(new Date(startDate).toISOString(), "MMMM d")} -{" "}
                        {format(
                          new Date(endDate).toISOString(),
                          "MMMM d, yyyy",
                        )}
                      </>
                    )}
                    <div className="text-sm text-primary/80">
                      {/* Start and end dates */}
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <User className="h-5 w-5" />
                <div>
                  <div className="text-sm text-primary/80">Organized by</div>
                  <div className="font-medium">
                    {organizer.firstName} {organizer.lastName}
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-col items-center gap-4 min-[400px]:flex-row">
              <Link className="h-full w-full" href={`/register/${id}`}>
                <Button
                  className={cn("group w-full min-[400px]:w-auto", {
                    "bg-red-500": new Date() > registrationClose,
                  })}
                  disabled={new Date() > registrationClose}
                >
                  Apply Now
                  <ChevronRight className="ml-2 h-5 w-0 opacity-0 transition-all duration-150 group-hover:w-5 group-hover:opacity-100" />
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>
      {/* <section className="w-full border-b bg-black text-primary">
        <Image
          src={photo}
          alt={name}
          layout="responsive"
          width={1920}
          height={1080}
        />
      </section> */}
      <section className="w-full pt-12">
        <div className="container px-4 md:px-6">
          <div className="grid gap-8">
            <div>
              <h2 className="text-2xl font-bold">About</h2>
              <p className="mt-4">{description}</p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12">
        <div className="container px-4 md:px-6">
          <div className="grid gap-8">
            <div>
              <h2 className="text-2xl font-bold">Registration Details</h2>
              <div className="mt-4 grid gap-4">
                <div className="flex items-center gap-2">
                  <Calendar className="h-5 w-5" />
                  <div>
                    <div className="font-medium">Registration Opens</div>
                    <div className="text-muted-foreground">
                      {format(
                        new Date(registrationOpen).toISOString(),
                        "MMMM d, yyyy",
                      )}
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Calendar className="h-5 w-5" />
                  <div>
                    <div className="font-medium">Registration Closes</div>
                    <div className="text-muted-foreground">
                      {format(
                        new Date(registrationClose).toISOString(),
                        "MMMM d, yyyy",
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <h2 className="text-2xl font-bold">Location</h2>
              <div className="mt-4 grid gap-4">
                <div className="flex items-center gap-2">
                  <MapPin className="h-5 w-5" />
                  <div>
                    <div className="font-medium">{location}</div>
                    {/* <div className="text-muted-foreground">
                      123 Main St, Anytown USA
                    </div> */}
                  </div>
                </div>
              </div>
            </div>
            <div>
              <h2 className="text-2xl font-bold">Team Size</h2>
              <div className="mt-4 grid gap-4">
                <div className="flex items-center gap-2">
                  <Users className="h-5 w-5" />
                  <div>
                    <div className="font-medium">Team Size</div>
                    <div className="text-muted-foreground">
                      {minTeamSize == maxTeamSize
                        ? minTeamSize
                        : `${minTeamSize} - ${maxTeamSize}`}{" "}
                      members
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
