/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YDDXoLu7Rlq
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { Button } from "~/components/ui/button";

export function HackathonPage() {
  return (
    <div className="flex min-h-[100dvh] flex-col">
      <section className="w-full bg-black text-primary">
        <div className="flex flex-col justify-center space-y-6 py-12 md:py-24 lg:py-32">
          <div className="space-y-4">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-6xl xl:text-7xl/none">
              Hackathon 2024
            </h1>
            <p className="max-w-[600px] text-primary/80 md:text-xl">
              Join us for an exciting 48-hour hackathon where you can showcase
              your skills and build innovative solutions.
            </p>
            <div className="flex flex-col items-center gap-4 min-[400px]:flex-row">
              <div className="flex items-center gap-2">
                <CalendarIcon className="h-5 w-5" />
                <div>
                  <div className="font-medium">June 1 - June 3, 2024</div>
                  {/* <div className="text-sm text-primary/80">
                    Start and end dates
                  </div> */}
                </div>
              </div>
              <div className="flex items-center gap-2">
                <UserIcon className="h-5 w-5" />
                <div>
                  <div className="text-sm text-primary/80">Organized by</div>
                  <div className="font-medium">Acme Inc.</div>
                </div>
              </div>
            </div>
            <div className="flex flex-col items-center gap-4 min-[400px]:flex-row">
              <Button className="w-full min-[400px]:w-auto">Apply Now</Button>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="grid gap-8">
            <div>
              <h2 className="text-2xl font-bold">Registration Details</h2>
              <div className="mt-4 grid gap-4">
                <div className="flex items-center gap-2">
                  <CalendarIcon className="h-5 w-5" />
                  <div>
                    <div className="font-medium">Registration Opens</div>
                    <div className="text-muted-foreground">April 1, 2024</div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <CalendarIcon className="h-5 w-5" />
                  <div>
                    <div className="font-medium">Registration Closes</div>
                    <div className="text-muted-foreground">May 31, 2024</div>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <h2 className="text-2xl font-bold">Location</h2>
              <div className="mt-4 grid gap-4">
                <div className="flex items-center gap-2">
                  <MapPinIcon className="h-5 w-5" />
                  <div>
                    <div className="font-medium">Acme HQ</div>
                    <div className="text-muted-foreground">
                      123 Main St, Anytown USA
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <h2 className="text-2xl font-bold">Team Size</h2>
              <div className="mt-4 grid gap-4">
                <div className="flex items-center gap-2">
                  <UsersIcon className="h-5 w-5" />
                  <div>
                    <div className="font-medium">Team Size</div>
                    <div className="text-muted-foreground">3 - 5 members</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  );
}

function MapPinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  );
}

function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}

function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  );
}

function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
